-- create "users" table
CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp NOT NULL, "updated_at" timestamp NULL, "deleted_at" timestamp NULL, "age" bigint NOT NULL, "name" character varying NOT NULL, "password" character varying NOT NULL, PRIMARY KEY ("id"));
-- create index "users_name_key" to table: "users"
CREATE UNIQUE INDEX "users_name_key" ON "users" ("name");
